feat: Scrapper file download  function develop
hell-of-sloth/skkubot pull request #13
Opened 2024-01-12 13:46 UTC by jnnkk

- 첨부파일 스크래핑 기능 추가
- 한 본문당 여러개일 경우 압축된 파일로 받는 것도 가능

- 첨부파일 내용을 다 까야되는 건지? 의견바람

2024-01-12 16:05 UTC, gyunseo requested changes

2024-01-12 16:05 UTC, gyunseo commented on scrapper/scrapper.js
>          .findElement(By.css("pre.pre"))
제가 짠 부분이긴 하지만, 공지사항 글마다 글 본문의 class가 다른 경우가 있더라고요. 이를 해결 할 수 있게 코드 수정이 필요해 보입니다.

2024-01-12 16:07 UTC, gyunseo requested changes
ㅇㅌ

2024-01-12 16:15 UTC, gyunseo requested changes
ㅇㅇㅇ

2024-01-12 16:16 UTC, gyunseo approved these changes

2024-01-12 16:16 UTC, gyunseo requested changes
ㄹㅇㄴㅁㄹㅇㄴ

2024-01-12 16:18 UTC, gyunseo commented on scrapper/scrapper.js
> +          .findElement(By.css("li"))
test

2024-01-12 16:19 UTC, gyunseo commented on scrapper/scrapper.js
> +}
test

2024-01-12 16:20 UTC, gyunseo commented on scrapper/scrapper.js
>          .findElement(By.css("pre.pre"))
이거 제가 짠 코드이기는 한데요. 공지사항 본문이 모두다 css("pre.pre")로 선택되지 않아서, 오류가 나더라고요. 그래서 이걸 핸들링하는 케이스를 고려해서 다시 짜야 합니다.

2024-01-12 16:21 UTC, gyunseo approved these changes

2024-01-12 16:37 UTC, gyunseo requested changes
제가 코드를 짜면서 TODO comment로 적은 것인데요. for 문을 돌려서 순차적으로 scrapping해도 되지만, nodejs의 특징 single thread nonblocking 이점을 살려서, `Promise.all`이나 `Promise.allSettled`를 이용해서 (제 생각에는 error가 나도 병렬처리가 중단되지 않는 allSettled가 더 좋을 것 같습니다.) scrapping 코드를 짜는 게 어떨지 생각해 봅니다.

2024-01-15 05:29 UTC, jnnkk commented
- 본문 css 셀렉터가 다른 형식이 있을때 처리하는 로직을 만들었습니다
- 전체 url에 Promise.allsettled를 적용하려 했지만 Selenium의 크롤링 형식 때문인지 다른 문제인지 작동하지 않음

2024-01-16 04:49 UTC, gyunseo requested changes

2024-01-16 04:49 UTC, gyunseo commented on scrapper/inverter.py
> +from win32com import client # pywin32 패키지 설치 필요
package 설치 pipenv로 설정 가능할까요?

2024-01-16 05:25 UTC, gyunseo commented on scrapper/inverter.py
> +from win32com import client # pywin32 패키지 설치 필요
pipenv로 해도 local machine이 windows냐 mac이냐 linux에 따라 package 설치에 오류가 있어서, 그냥 devcontainer로 진행하기로 했습니다. devcontainer로 바뀌면 merge하도록 하겠습니다.

2024-01-26 05:19 UTC, closed without merging